/**
 * Log sanitization utilities shared by `logger` and the error reporter.
 *
 * Both the console pipeline and the Supabase `errors` pipeline call into this
 * module so that the same redaction policy is enforced before any sensitive
 * value can leak to Cloudflare Workers logs, GitHub Issues (auto-generated by
 * twica-error-reporter), or the Supabase errors table.
 *
 * Key categories follow OWASP Logging Cheat Sheet recommendations:
 * - PARTIAL_SENSITIVE_KEYS: substring match — always redact when the key
 *   contains one of these tokens (e.g. `twitch_access_token`, `csrf_token`).
 * - EXACT_SENSITIVE_KEYS: exact match only — redact bare PII keys without
 *   masking debug-friendly compound keys (e.g. `userId` is masked but
 *   `broadcasterUserId` / `twitchUsername` are kept for triage).
 */

const PARTIAL_SENSITIVE_KEYS = [
  'password', 'passwd', 'pwd', 'token', 'authorization', 'bearer',
  'cookie', 'secret', 'apikey', 'api_key', 'api-key',
  'access_token', 'refresh_token', 'client_secret',
  'credential', 'private_key',
  'session_id', 'sessionid', 'otp', 'auth_code',
  'csrf_token', 'xsrf_token',
]

const EXACT_SENSITIVE_KEYS = ['userid', 'username', 'email', 'ip_address']

export function isSensitiveKey(key: string): boolean {
  const lowerKey = key.toLowerCase()
  if (EXACT_SENSITIVE_KEYS.some(k => lowerKey === k)) return true
  if (PARTIAL_SENSITIVE_KEYS.some(k => lowerKey.includes(k))) return true
  return false
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

/**
 * Recursively replace sensitive values with `[REDACTED]`.
 * Pure function — input is not mutated.
 */
export function sanitizeContext(obj: Record<string, unknown>): Record<string, unknown> {
  const sanitized: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(obj)) {
    if (isSensitiveKey(key)) {
      sanitized[key] = '[REDACTED]'
    } else if (Array.isArray(value)) {
      sanitized[key] = value.map(item => isRecord(item) ? sanitizeContext(item) : item)
    } else if (isRecord(value)) {
      sanitized[key] = sanitizeContext(value)
    } else {
      sanitized[key] = value
    }
  }
  return sanitized
}

/**
 * Sanitize a single log argument for console output.
 * - Plain records are sanitized recursively.
 * - Error instances are passed through (their `.message` / `.stack` are
 *   developer-authored and assumed not to embed secrets).
 * - Primitives are passed through.
 *
 * Note: arrays of primitives pass through unchanged; arrays of objects are
 * sanitized so structures like `[{ token: '...' }]` are still masked.
 */
export function sanitizeLogArg(arg: unknown): unknown {
  if (arg instanceof Error) return arg
  if (Array.isArray(arg)) {
    return arg.map(item => isRecord(item) ? sanitizeContext(item) : item)
  }
  if (isRecord(arg)) return sanitizeContext(arg)
  return arg
}

/**
 * Extract a readable message from an unknown error.
 * Plain objects with a string `message` (e.g. Supabase PostgrestError) are
 * supported. Otherwise we fall back to JSON.stringify with sensitive-key
 * redaction and circular-reference safety.
 *
 * See: https://github.com/azumag/twica/issues/262
 */
export function extractErrorMessage(error: unknown): string {
  if (error && typeof error === 'object') {
    if ('message' in error && typeof (error as { message: unknown }).message === 'string') {
      return (error as { message: string }).message
    }
    const seen = new WeakSet()
    try {
      return JSON.stringify(error, (key, value) => {
        if (key && isSensitiveKey(key)) return '[REDACTED]'
        if (typeof value === 'object' && value !== null) {
          if (seen.has(value)) return '[Circular]'
          seen.add(value)
        }
        return value
      })
    } catch {
      return '[Unserializable object]'
    }
  }
  return String(error)
}
