/**
 * Log sanitization utilities shared by `logger` and the error reporter.
 *
 * Both the console pipeline and the PlanetScale `errors` pipeline call into this
 * module so that the same redaction policy is enforced before any sensitive
 * value can leak to Cloudflare Workers logs, GitHub Issues (auto-generated by
 * twica-error-reporter), or the errors table.
 *
 * Key categories follow OWASP Logging Cheat Sheet recommendations:
 * - PARTIAL_SENSITIVE_KEYS: substring match — always redact when the key
 *   contains one of these tokens (e.g. `twitch_access_token`, `csrf_token`).
 * - EXACT_SENSITIVE_KEYS: exact match only — redact bare sensitive/PII keys
 *   without masking debug-friendly compound keys (e.g. `userId` is masked but
 *   `broadcasterUserId` / `twitchUsername` are kept for triage).
 */

const PARTIAL_SENSITIVE_KEYS = [
  'password', 'passwd', 'pwd', 'token', 'authorization', 'bearer',
  'cookie', 'secret', 'apikey', 'api_key', 'api-key',
  'access_token', 'refresh_token', 'client_secret',
  'credential', 'private_key',
  'session_id', 'sessionid', 'otp', 'auth_code',
  'csrf_token', 'xsrf_token',
]

// DrizzleQueryError.params は bind 値（token 等）を保持し得るため、汎用名でも exact match で隠す。
const EXACT_SENSITIVE_KEYS = ['userid', 'username', 'email', 'ip_address', 'params']

// postgres.js の PostgresError はこれらを own enumerable field として持ち、
// DETAIL / WHERE や debug bind 情報に行データ・token 等が含まれ得る。
// 汎用 context の `detail` 等まで消さないよう、Error field を再構築する時だけ適用する。
const ERROR_EXACT_SENSITIVE_KEYS = ['detail', 'where', 'parameters', 'args']

const MAX_SANITIZE_DEPTH = 8
const CIRCULAR_MARKER = '[Circular]'
const MAX_DEPTH_MARKER = '[MaxDepth]'

// drizzle-orm の DrizzleQueryError は bind 値を `params:` 以降へ埋め込み得る。
// bind 値自体に改行が含まれる場合もあるため、次の stack frame（`    at ...`）
// または文字列末尾までを一括で置換し、stack frame だけを診断用に残す。
const DRIZZLE_PARAMS_BLOCK = /^([^\S\r\n]*params:[^\S\r\n]*)(?:[^\r\n]*(?:\r?\n(?![^\S\r\n]+at\s)[^\r\n]*)*)/gim

export function isSensitiveKey(key: string): boolean {
  const lowerKey = key.toLowerCase()
  if (EXACT_SENSITIVE_KEYS.some(k => lowerKey === k)) return true
  if (PARTIAL_SENSITIVE_KEYS.some(k => lowerKey.includes(k))) return true
  return false
}

function isSensitiveErrorKey(key: string): boolean {
  const lowerKey = key.toLowerCase()
  return isSensitiveKey(key) || ERROR_EXACT_SENSITIVE_KEYS.includes(lowerKey)
}

export function sanitizeErrorText(value: string): string {
  return value.replace(DRIZZLE_PARAMS_BLOCK, '$1[REDACTED]')
}

function isRecord(v: unknown): v is Record<string, unknown> {
  return typeof v === 'object' && v !== null && !Array.isArray(v)
}

function sanitizeRecord(
  obj: Record<string, unknown>,
  depth: number,
  seen: WeakSet<object>,
  errorFields = false,
): Record<string, unknown> {
  const sanitized: Record<string, unknown> = {}
  for (const [key, value] of Object.entries(obj)) {
    const sensitive = errorFields ? isSensitiveErrorKey(key) : isSensitiveKey(key)
    sanitized[key] = sensitive
      ? '[REDACTED]'
      : sanitizeValue(value, depth + 1, seen)
  }
  return sanitized
}

function sanitizeErrorForLogInternal(
  error: Error,
  depth: number,
  seen: WeakSet<object>,
): Error {
  const sanitized = new Error(sanitizeErrorText(error.message))
  sanitized.name = error.name
  if (error.stack) sanitized.stack = sanitizeErrorText(error.stack)

  // Error の custom enumerable fields（query / params / cause / code 等）も console 展開時に
  // 見えるため、Error 固有の機密fieldを含むキー名ベースのポリシーを適用する。
  Object.assign(
    sanitized,
    sanitizeRecord(Object.fromEntries(Object.entries(error)), depth, seen, true),
  )
  return sanitized
}

function sanitizeValue(value: unknown, depth: number, seen: WeakSet<object>): unknown {
  if (typeof value === 'string') return sanitizeErrorText(value)
  if (typeof value !== 'object' || value === null) return value
  if (depth >= MAX_SANITIZE_DEPTH) return MAX_DEPTH_MARKER
  if (seen.has(value)) return CIRCULAR_MARKER

  seen.add(value)
  try {
    if (value instanceof Error) return sanitizeErrorForLogInternal(value, depth, seen)
    if (Array.isArray(value)) {
      // 既存契約どおり配列は1段だけ処理し、ネスト配列の再帰化は別フォローアップに残す。
      return value.map(item => {
        if (item instanceof Error || isRecord(item)) {
          return sanitizeValue(item, depth + 1, seen)
        }
        if (typeof item === 'string') return sanitizeErrorText(item)
        return item
      })
    }
    return sanitizeRecord(value as Record<string, unknown>, depth, seen)
  } finally {
    seen.delete(value)
  }
}

function sanitizeErrorForLog(error: Error): Error {
  const seen = new WeakSet<object>()
  seen.add(error)
  try {
    return sanitizeErrorForLogInternal(error, 0, seen)
  } finally {
    seen.delete(error)
  }
}

/**
 * Recursively replace sensitive values with `[REDACTED]`.
 * Pure function — input is not mutated.
 */
export function sanitizeContext(obj: Record<string, unknown>): Record<string, unknown> {
  const seen = new WeakSet<object>()
  seen.add(obj)
  try {
    return sanitizeRecord(obj, 0, seen)
  } finally {
    seen.delete(obj)
  }
}

/**
 * Sanitize a single log argument for console output.
 * - Plain records are sanitized recursively.
 * - Error instances keep their Error shape, but message / stack and enumerable
 *   fields are sanitized because library-generated errors may embed bind values.
 * - Primitives are passed through.
 *
 * Note: arrays of primitives pass through except string values, which still
 * receive the error-text redaction used for Drizzle-style `params:` lines.
 */
export function sanitizeLogArg(arg: unknown): unknown {
  if (arg instanceof Error) return sanitizeErrorForLog(arg)
  if (Array.isArray(arg)) return sanitizeValue(arg, 0, new WeakSet<object>())
  if (isRecord(arg)) return sanitizeContext(arg)
  if (typeof arg === 'string') return sanitizeErrorText(arg)
  return arg
}

/**
 * Extract a readable message from an unknown error.
 * Plain objects with a string `message` (e.g. PostgreSQL driver errors) are
 * supported. Otherwise we fall back to JSON.stringify with sensitive-key
 * redaction and circular-reference safety.
 *
 * See: https://github.com/azumag/twica/issues/262
 */
export function extractErrorMessage(error: unknown): string {
  if (error && typeof error === 'object') {
    if ('message' in error && typeof (error as { message: unknown }).message === 'string') {
      return sanitizeErrorText((error as { message: string }).message)
    }
    const seen = new WeakSet()
    try {
      return sanitizeErrorText(JSON.stringify(error, (key, value) => {
        if (key && isSensitiveKey(key)) return '[REDACTED]'
        if (typeof value === 'object' && value !== null) {
          if (seen.has(value)) return '[Circular]'
          seen.add(value)
        }
        return value
      }))
    } catch {
      return '[Unserializable object]'
    }
  }
  return sanitizeErrorText(String(error))
}
