/**
 * Error Reporting Abstraction Layer
 * エラーレポート抽象レイヤー
 *
 * Sentry SDK was removed to reduce bundle size for Cloudflare Workers deployment
 * (Sentry was duplicated 4x by Turbopack, consuming ~16.8MB of the 23MB bundle).
 * This layer is maintained as an abstraction so that error monitoring can be
 * re-enabled by changing only the implementation in this file.
 *
 * 現在の実装: console.error + errors テーブルへの記録
 * DB に記録されたエラーは Cron Worker (twica-error-reporter) が
 * 定期的に読み出して GitHub Issue を自動作成する。
 *
 * See: https://github.com/azumag/twica/issues/235 (Sentry削除)
 * See: https://github.com/azumag/twica/issues/239 (エラー監視再導入)
 */

/**
 * errors テーブルへの記録方針:
 * - サーバーサイド (Cloudflare Workers) でのみ動作
 * - クライアントサイドでは記録処理を実行しない
 * - DB への記録失敗はメインのエラー処理を阻害しない
 * - DB_DRIVER=pg はDrizzle、その他は従来のPostgRESTを使う
 *
 * dynamic import する理由:
 * - error-handler.ts はクライアント・サーバー両方からインポートされる
 * - サーバーサイドでのみ Supabase クライアントをロードする
 *
 * 機密情報マスキング:
 * - sanitizeContext / extractErrorMessage は log-sanitizer.ts に集約
 * - 同じユーティリティを logger.ts も使用しており、console 経路 / Supabase 経路で
 *   同一ポリシーが適用される（Issue #401）
 * - Sensitive-info masking lives in log-sanitizer so both the console pipeline
 *   (logger) and the Supabase pipeline use the same redaction policy.
 */

import { sanitizeContext, extractErrorMessage } from '@/lib/log-sanitizer'
import type { Json } from '@/types/database'

/**
 * error から message と stack を統一的に解決する。
 * 全 report*Error 関数の if/else 分岐を集約し DRY 原則を維持する。
 */
function resolveErrorInfo(error: unknown): { message: string; stack: string | null; isErrorInstance: boolean } {
  if (error instanceof Error) {
    return { message: error.message, stack: error.stack || null, isErrorInstance: true }
  }
  return { message: extractErrorMessage(error), stack: null, isErrorInstance: false }
}

// PostgreSQL TEXT 型は最大1GBだが、実用的な上限として定数化
const MAX_MESSAGE_LENGTH = 10000
const MAX_STACK_LENGTH = 50000

function persistedContext(context: Record<string, unknown>): Json {
  // Drizzle intentionally accepts only JSON-compatible values for jsonb.  A
  // stringify/parse round-trip both validates the runtime value and removes
  // unsupported `undefined` properties before the insert; the cast is safe
  // because JSON.parse can only produce the Json union declared by the schema.
  const serialized = JSON.stringify(sanitizeContext(context))
  return JSON.parse(serialized) as Json
}

async function logErrorToDatabase(
  errorType: string,
  message: string,
  stackTrace: string | null,
  context: Record<string, unknown>
): Promise<void> {
  // Client bundles import this module through logger/realtime code, but the
  // Supabase error table requires server-only service-role credentials.
  if (typeof window !== 'undefined' && process.env.NODE_ENV !== 'test') {
    return
  }

  try {
    // 環境判定: NEXT_PUBLIC_APP_URL に 'preview' が含まれるかで判定
    const appUrl = process.env.NEXT_PUBLIC_APP_URL || ''
    const environment = appUrl.includes('preview') ? 'preview' : 'production'
    const values = {
      error_type: errorType,
      message: message.slice(0, MAX_MESSAGE_LENGTH),
      stack_trace: stackTrace?.slice(0, MAX_STACK_LENGTH) || null,
      // 機密情報（userId, token 等）を除外してから記録
      context: persistedContext(context),
      environment,
    }

    // NEXT_RUNTIME is replaced at build time by Next.js. The browser build sees
    // this branch as unreachable and removes the postgres.js import graph
    // (net/tls/fs are unavailable in browsers), while node/edge server bundles
    // retain it. A runtime-only `typeof window` guard is insufficient because
    // webpack still resolves dynamic imports before that check executes.
    if (process.env.NEXT_RUNTIME) {
      // flags は環境変数だけを見る軽量moduleなので先に単独で読み込む。
      // client/schema/retry はPG書き込みが有効な場合にだけ評価し、postgrestや
      // pg-read環境の既存エラー記録をPG moduleのimport失敗へ巻き込まない。
      const { isPgWriteEnabled } = await import('@/lib/db/flags')

      if (isPgWriteEnabled()) {
        const [{ getDb }, { withDbRetry }, { errors }] = await Promise.all([
          import('@/lib/db/client'),
          import('@/lib/db/retry'),
          import('@/lib/db/schema'),
        ])
        // errors.id is generated by the database, so a connection loss can leave
        // commit outcome unknown. Until #711's owner decision on duplicate-vs-loss
        // semantics, keep idempotent=false (the safe default) and never retry an
        // ambiguous insert automatically.
        await withDbRetry(async () => {
          const { db } = await getDb()
          return db.insert(errors).values(values)
        }, 'error tracking insert')
        return
      }
    }

    const { getSupabaseAdmin } = await import('@/lib/supabase/admin')
    const supabase = getSupabaseAdmin()

    await supabase.from('errors').insert(values)
  } catch (err) {
    // エラーDBへの記録失敗はメインのエラー処理を阻害しない
    // エラー詳細を出力して Cloudflare Workers Observability (wrangler tail) で確認可能にする
    // logger.error は logErrorFromLogger() を経由してこの関数へ戻るため使用禁止。
    // console.warn を直接使うことを再帰防止の唯一の仕組みにし、同一isolate内の別
    // requestで同じエラーが並行発生しても観測データを誤って捨てない。
    console.warn('[Error Tracking] Failed to persist error:', err)
  }
}

// Issue #401: console 経路と Supabase 経路で同一マスキングポリシーを適用するため、
// report*Error 系も console 出力前に context をサニタイズする。Cloudflare Workers logs /
// wrangler tail に raw な OAuth token 等が漏れることを防止する。
// Sanitize context for console output to enforce the same redaction policy
// across both pipelines (Cloudflare Workers logs and Supabase errors table).
function consoleContext(context: Record<string, unknown> | undefined): Record<string, unknown> | string {
  if (!context) return ''
  return sanitizeContext(context)
}

export async function reportError(error: Error | unknown, context?: Record<string, unknown>) {
  const info = resolveErrorInfo(error)
  // Error インスタンスは [Error] + console.error、それ以外は [Warning] + console.warn
  const label = info.isErrorInstance ? '[Error]' : '[Warning]'
  const log = info.isErrorInstance ? console.error : console.warn
  log(label, info.message, consoleContext(context))
  await logErrorToDatabase(label, info.message, info.stack, context || {})
}

export async function reportApiError(endpoint: string, method: string, error: Error | unknown, additionalContext?: Record<string, unknown>) {
  const label = `${method} ${endpoint}`
  const ctx = { endpoint, method, ...additionalContext }
  const { message, stack } = resolveErrorInfo(error)
  console.error(`[API Error] ${label}:`, message, consoleContext(additionalContext))
  await logErrorToDatabase('[API Error]', `${label}: ${message}`, stack, ctx)
}

export async function reportAuthError(error: Error | unknown, context: { provider?: string; action?: string; userId?: string }) {
  const { message, stack } = resolveErrorInfo(error)
  console.error('[Auth Error]', message, sanitizeContext(context as Record<string, unknown>))
  await logErrorToDatabase('[Auth Error]', message, stack, context)
}

export async function reportGachaError(error: Error | unknown, context: { streamerId?: string; userId?: string; cost?: number }) {
  const { message, stack } = resolveErrorInfo(error)
  console.error('[Gacha Error]', message, sanitizeContext(context as Record<string, unknown>))
  await logErrorToDatabase('[Gacha Error]', message, stack, context)
}

export async function reportBattleError(error: Error | unknown, context: { battleId?: string; userId?: string; round?: number }) {
  const { message, stack } = resolveErrorInfo(error)
  console.error('[Battle Error]', message, sanitizeContext(context as Record<string, unknown>))
  await logErrorToDatabase('[Battle Error]', message, stack, context)
}

export async function reportRealtimeError(error: unknown, context: { action?: string; streamerId?: string; status?: string; retryCount?: number; isExpected?: boolean }) {
  // Suppress expected connection events (CLOSED, TIMED_OUT, CHANNEL_ERROR)
  // to avoid noise in logs, matching previous Sentry behavior
  // 期待されるステータスはログもSupabase記録もスキップ
  const EXPECTED_STATUSES = ['CLOSED', 'TIMED_OUT', 'CHANNEL_ERROR']

  if (context.isExpected || (context.status && EXPECTED_STATUSES.includes(context.status))) {
    return
  }

  const { message, stack } = resolveErrorInfo(error)
  console.error('[Realtime Error]', message, sanitizeContext(context as Record<string, unknown>))
  await logErrorToDatabase('[Realtime Error]', message, stack, context)
}

export async function reportSecurityError(error: Error | unknown, context: { action?: string; userId?: string; [key: string]: unknown }) {
  const { message, stack } = resolveErrorInfo(error)
  console.error('[Security Error]', message, sanitizeContext(context))
  await logErrorToDatabase('[Security Error]', message, stack, context)
}

/**
 * logger.error から呼ばれる Supabase 記録専用関数。
 * console 出力は logger.error 側で行うため、ここでは Supabase 記録のみ。
 * args から Error と context を自動抽出する。
 */
export async function logErrorFromLogger(message: string, args: unknown[]): Promise<void> {
  try {
    let stack: string | null = null
    const context: Record<string, unknown> = {}
    let errorDetail = ''

    for (const arg of args) {
      if (arg instanceof Error) {
        // 最初の Error を採用（原因エラーは通常先頭に渡される）
        if (!errorDetail) {
          errorDetail = arg.message
          stack = arg.stack || null
        }
      } else if (arg && typeof arg === 'object') {
        const obj = arg as Record<string, unknown>
        // { error: ... } パターンからエラー詳細を抽出
        if ('error' in obj && obj.error != null && !errorDetail) {
          if (obj.error instanceof Error) {
            errorDetail = (obj.error as Error).message
            stack = (obj.error as Error).stack || null
          } else {
            errorDetail = extractErrorMessage(obj.error)
          }
        } else if (!errorDetail && 'message' in obj && typeof obj.message === 'string' && obj.message !== '') {
          // error プロパティがない場合、オブジェクト自体が PostgrestError 等のエラーと判定
          // See: https://github.com/azumag/twica/issues/262
          errorDetail = obj.message
        }
        Object.assign(context, obj)
      }
    }

    const fullMessage = errorDetail ? `${message} ${errorDetail}` : message
    await logErrorToDatabase('[Error]', fullMessage, stack, context)
  } catch {
    // Supabase 報告失敗はメイン処理を阻害しない
  }
}
