// Claude 自動レビュー本文の整形・判定ロジック（純関数）。
// workflow の inline JS から切り出し、tests/unit/claude-review-format.test.ts で
// 検証する。伏字化は正規表現ベースのベストエフォートな緩和であり、最終防壁は
// workflow 側の生トークン完全一致チェック（トークンへ到達できる唯一の job にある）。
// 変更時は必ずテストを更新すること。

// 既知のトークン形式。GitHub のシークレットマスキングはログにのみ効き、
// API のコメント本文には適用されないため、投稿前に伏字化する。
// 末尾に否定先読みも \b も付けない: いずれも実トークンが素通りする fail-open に
// なるため（`ghp_..._` / `github_pat_...-` / `Xsk-ant-...` 等）。過剰伏字化は安全側。
const SECRET_PATTERN =
  /(sk-ant-[A-Za-z0-9_-]{10,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})/g

// プロンプトの 6000 字指示を実質的に守るためのしきい値（2.5 倍の余裕）。
// issue comment 上限 65536 には余裕を持って収まる。
export const MAX_BODY_LENGTH = 15000

export function redactSecrets(text) {
  // String.prototype.replace は /g 正規表現の lastIndex を走査前後にリセットする
  // ため、モジュール定数を共有して安全。stateful な .test()/.exec() には使わないこと。
  return text.replace(SECRET_PATTERN, '[REDACTED]')
}

// 本文長が上限を超えた場合は切り詰める。未閉じのコードフェンス（Claude の出力で
// 実測される）は切り詰めの有無に関わらず補完し、切り詰め時はフェンスを閉じてから
// 省略注記を足す。
// 返り値は本文部分を MAX_BODY_LENGTH 以内に保ち、閉じフェンスと注記を加算する
// （最大 +16 コードポイント。issue comment 上限 65536 に対して十分な余裕がある）。
export function truncateAndCloseFences(text) {
  const needsTruncation = text.length > MAX_BODY_LENGTH
  let result = text
  if (needsTruncation) {
    result = text.slice(0, MAX_BODY_LENGTH)
    // 行途中で切れた不完全行を落とす（フェンスの途中切断で補完が破綻するのを防ぐ）
    const lastNewline = result.lastIndexOf('\n')
    if (lastNewline > 0) {
      result = result.slice(0, lastNewline)
    }
    // 末尾が孤立サロゲート（絵文字の片割れ）なら除去し、JSON 化での文字化けを防ぐ
    result = result.replace(/[\uD800-\uDBFF]$/, '')
  }
  if (needsTruncation) {
    // 切り詰め時のみフェンスを補完する。非切り詰め時はレビュー本文がコード
    // 引用を多く含み、行頭 ``` の偶奇ヒューリスティックが誤判定しやすいため
    // 触らない（フッターがコードブロックに飲み込まれるのは表示崩れのみ）。
    const fenceCount = result
      .split('\n')
      .filter((line) => line.trim().startsWith('```')).length
    if (fenceCount % 2 === 1) {
      result += '\n```'
    }
    result += '\n\n（長すぎるため省略）'
  }
  return result
}

// structured_output の JSON から review 本文を取り出す。
// review フィールドが空・空白のみ、または JSON として壊れている場合は throw する
// （workflow 側で failure にする。空・空白は jq の早期チェックでも弾かれるため、
//  ここは後段の防御）。
export function parseReviewJson(json) {
  const { review } = JSON.parse(json)
  if (typeof review !== 'string' || review.trim() === '') {
    // 空・空白・型違いも JSON として不成立扱いにする（jq の早期チェックで
    // 既に弾かれるため、ここは後段の防御）。
    throw new Error('invalid')
  }
  return review.trim()
}

// 投稿本文・Step summary の両方に適用する共通サニタイズ
// （伏字化 → 切り詰めの順序をここに固定する）。
export function sanitizeReviewText(reviewText) {
  return truncateAndCloseFences(redactSecrets(reviewText))
}

// 整形済み本文（sanitizeReviewText の出力）から投稿コメント本文を組み立てる。
export function buildReviewCommentBody({ marker, shortSha, commitUrl, runUrl, safeText }) {
  return (
    `${marker}\n## Claude Auto Review\n\n` +
    `Reviewed commit: [\`${shortSha}\`](${commitUrl})\n\n` +
    `${safeText}\n\n` +
    `*Generated by Claude Code (opus) · [Run](${runUrl})*`
  )
}

// コメント一覧からこのワークフローが投稿したレビューコメントを探す。
// マーカーは誰でも知り得るため、投稿者を呼び出し側（workflow の github-token が
// 生み出す投稿者ログイン）に限定して第三者（他のボット含む）コメントの誤上書きを
// 防ぐ。
export function findOwnReviewComment(comments, marker, authorLogin) {
  // 重複投稿の競合（キャンセルと新 run のタイミング）で古いコメントが残る場合に
  // 最新を更新対象にするため、末尾から探す。
  return comments.findLast(
    (comment) =>
      comment?.user?.login === authorLogin &&
      // 先頭行がマーカーかどうか（GitHub API が \r\n を返し得るため trim する）
      comment.body?.split('\n', 1)[0].trim() === marker,
  )
}
