// Claude 自動レビュー本文の整形・判定ロジック（純関数）。
// workflow の inline JS から切り出し、tests/unit/claude-review-format.test.ts で
// 検証する。伏字化は正規表現ベースのベストエフォートな緩和であり、最終防壁は
// workflow 側の生トークン完全一致チェック（トークンへ到達できる唯一の job にある）。
// 変更時は必ずテストを更新すること。

// 既知のトークン形式。GitHub のシークレットマスキングはログにのみ効き、
// API のコメント本文には適用されないため、投稿前に伏字化する。
// 末尾に否定先読みも \b も付けない: いずれも実トークンが素通りする fail-open に
// なるため（`ghp_..._` / `github_pat_...-` / `Xsk-ant-...` 等）。過剰伏字化は安全側。
const SECRET_PATTERN =
  /(sk-ant-[A-Za-z0-9_-]{10,}|gh[pousr]_[A-Za-z0-9]{20,}|github_pat_[A-Za-z0-9_]{20,})/g

// issue comment 上限 65536 に対する安全網（外枠を差し引いても余裕を持つ）。
// プロンプトは 6000 字を指示しているが、超過時に指摘の後半を落とさないよう
// 実質発火しない大きめの値にする。
export const MAX_BODY_LENGTH = 60000

// レビューコメントの識別マーカー（単一の出典。workflow とテストはこれを参照する）。
export const REVIEW_MARKER = '<!-- claude-auto-review-preview -->'

export function redactSecrets(text) {
  // String.prototype.replace は /g 正規表現の lastIndex を走査前後にリセットする
  // ため、モジュール定数を共有して安全。stateful な .test()/.exec() には使わないこと。
  return text.replace(SECRET_PATTERN, '[REDACTED]')
}

// 本文長が上限を超えた場合は切り詰めて省略注記を足す（実質発火しない安全網。
// フェンス補完等のヒューリスティックは誤判定の方が害のため持たない）。
// 返り値は本文部分を MAX_BODY_LENGTH 以内に保ち、閉じフェンスと注記を加算する
// （注記は 12 コードポイント。issue comment 上限 65536 に対して十分な余裕がある）。
export function truncateAndCloseFences(text) {
  if (text.length <= MAX_BODY_LENGTH) {
    return text
  }
  return text.slice(0, MAX_BODY_LENGTH) + '\n\n（長すぎるため省略）'
}

// structured_output の JSON から review 本文（trim 済み）を取り出す。
// 空・空白の検証は claude_review job の jq チェックが担う（トークン到達 job で
// 切り分けるため）。ここでは JSON パースと型チェックのみ行い、壊れていれば throw する。
export function parseReviewJson(json) {
  const { review } = JSON.parse(json)
  if (typeof review !== 'string') {
    // 型違いは TypeError 依存にせず明示的に失敗させる（jq は別ジョブのため
    // ここでの前提にしない）。
    throw new TypeError('review field is not a string')
  }
  // 空・空白の検証は claude_review job の jq チェックが担う（トークン到達 job で
  // 切り分けるため）。ここでは型違いの明示チェックと JSON パースのみ扱う。
  return review.trim()
}

// 投稿本文・Step summary の両方に適用する共通サニタイズ
// （伏字化 → 切り詰めの順序をここに固定する）。
export function sanitizeReviewText(reviewText) {
  return truncateAndCloseFences(redactSecrets(reviewText))
}

// 整形済み本文（sanitizeReviewText の出力）から投稿コメント本文を組み立てる。
export function buildReviewCommentBody({ marker, shortSha, commitUrl, runUrl, safeText }) {
  return (
    `${marker}\n## Claude Auto Review\n\n` +
    `Reviewed commit: [\`${shortSha}\`](${commitUrl})\n\n` +
    `${safeText}\n\n` +
    `*Generated by Claude Code (opus) · [Run](${runUrl})*`
  )
}

// コメント一覧からこのワークフローが投稿したレビューコメントを探す。
// マーカーは誰でも知り得るため、投稿者を呼び出し側（workflow の github-token が
// 生み出す投稿者ログイン）に限定して第三者（他のボット含む）コメントの誤上書きを
// 防ぐ。
export function findOwnReviewComment(comments, marker, authorLogin) {
  // 重複投稿の競合（キャンセルと新 run のタイミング）で古いコメントが残る場合に
  // 最新を更新対象にするため、末尾から探す。
  return comments.findLast(
    (comment) =>
      comment?.user?.login === authorLogin &&
      // 先頭行がマーカーかどうか（GitHub API が \r\n を返し得るため trim する）
      comment.body?.split('\n', 1)[0].trim() === marker,
  )
}
