/**
 * Error Reporter Cron Worker
 * エラーレポーター定期実行Worker
 *
 * 5分ごとに Supabase errors テーブルから未処理エラーを取得し、
 * エラーをシグネチャでグループ化（重複排除）してから
 * GitHub Issue を自動作成する。
 *
 * Tail Workers (有料プラン必須) の無料代替として実装。
 * Cloudflare Workers Free プランの Cron Triggers を使用。
 *
 * See: https://github.com/azumag/twica/issues/239
 */

interface Env {
  SUPABASE_URL: string
  SUPABASE_SERVICE_ROLE_KEY: string
  GITHUB_TOKEN: string
  GITHUB_REPO_OWNER: string
  GITHUB_REPO_NAME: string
}

/** Supabase errors テーブルのレコード型 */
interface ErrorRecord {
  id: string
  error_type: string
  message: string
  stack_trace: string | null
  context: Record<string, unknown>
  environment: string
  created_at: string
}

/** 同一シグネチャのエラーをまとめたグループ */
interface ErrorGroup {
  signature: string
  errors: ErrorRecord[]
  count: number
  firstSeen: string
  lastSeen: string
}

/**
 * エラーシグネチャを生成する。
 * error_type + message の先頭行 + スタックトレースの先頭行 を組み合わせ、
 * 同一のエラーを1つの GitHub Issue にまとめるために使用。
 *
 * SHA-256 を使って固定長のハッシュにすることで、
 * Issue 本文内での検索・照合を容易にする。
 */
async function generateSignature(error: ErrorRecord): Promise<string> {
  const messageLine = error.message.split('\n')[0].slice(0, 200)
  const stackLine = error.stack_trace?.split('\n')[0]?.slice(0, 200) || ''
  const raw = `${error.error_type}:${messageLine}:${stackLine}`

  const encoder = new TextEncoder()
  const data = encoder.encode(raw)
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  const hashArray = Array.from(new Uint8Array(hashBuffer))
  // 先頭16文字で十分な一意性を確保（衝突確率は無視できるレベル）
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('').slice(0, 16)
}

/**
 * エラーをシグネチャでグループ化する。
 * 同一シグネチャのエラーは1つの GitHub Issue にまとめる。
 */
async function groupErrors(errors: ErrorRecord[]): Promise<ErrorGroup[]> {
  const groups = new Map<string, ErrorRecord[]>()

  for (const error of errors) {
    const sig = await generateSignature(error)
    if (!groups.has(sig)) {
      groups.set(sig, [])
    }
    groups.get(sig)!.push(error)
  }

  return Array.from(groups.entries()).map(([signature, errs]) => ({
    signature,
    errors: errs,
    count: errs.length,
    // errs は created_at ASC (FIFO) で取得されるため、最初=最古、最後=最新
    firstSeen: errs[0].created_at,
    lastSeen: errs[errs.length - 1].created_at,
  }))
}

/**
 * GitHub Issues API で既存 Issue を検索する。
 * Issue 本文に埋め込んだ Signature ハッシュで照合。
 * 既に同じエラーの Issue が存在する場合は重複作成を防止する。
 */
async function findExistingIssue(
  signature: string,
  env: Env
): Promise<{ number: number; url: string } | null> {
  const query = `repo:${env.GITHUB_REPO_OWNER}/${env.GITHUB_REPO_NAME} is:issue "Signature: ${signature}"`
  const url = `https://api.github.com/search/issues?q=${encodeURIComponent(query)}`

  const res = await fetch(url, {
    headers: {
      'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
      'Accept': 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'User-Agent': 'twica-error-reporter',
    },
  })

  if (!res.ok) {
    console.warn(`[Error Reporter] GitHub search API failed: ${res.status}`)
    return null
  }

  const data = await res.json() as { total_count: number; items: Array<{ number: number; html_url: string }> }
  if (data.total_count > 0) {
    return { number: data.items[0].number, url: data.items[0].html_url }
  }
  return null
}

/**
 * GitHub Issue を新規作成する。
 * Issue 本文にエラー詳細、発生回数、シグネチャを記載。
 * シグネチャは重複検索に使用されるため、フォーマットを変更しないこと。
 */
async function createGitHubIssue(
  group: ErrorGroup,
  env: Env
): Promise<{ number: number; url: string }> {
  const first = group.errors[0]

  // タイトル: 環境 + エラー種別 + メッセージ先頭（最大80文字）
  const title = `[${first.environment}] ${first.error_type} ${first.message.split('\n')[0]}`.slice(0, 80)

  // 本文: エラー詳細を構造化して記載
  // Signature は重複検索に使用するため、フォーマットを変更しないこと
  const body = `## Auto-generated Error Report

**Type**: \`${first.error_type}\`
**Environment**: ${first.environment}
**Occurrences**: ${group.count}x
**First Seen**: ${group.firstSeen}
**Last Seen**: ${group.lastSeen}

### Message
\`\`\`
${first.message.slice(0, 2000)}
\`\`\`

### Stack Trace
\`\`\`
${first.stack_trace?.slice(0, 3000) || 'N/A'}
\`\`\`

### Context
\`\`\`json
${JSON.stringify(first.context, null, 2).slice(0, 2000)}
\`\`\`

---
Signature: ${group.signature}
*Auto-generated by [twica-error-reporter](https://github.com/azumag/twica/issues/239)*`

  // ラベル: 自動生成であることを明示 + 環境名
  const labels = ['bug', 'auto-generated']
  if (first.environment !== 'production') {
    labels.push(first.environment)
  }

  const res = await fetch(
    `https://api.github.com/repos/${env.GITHUB_REPO_OWNER}/${env.GITHUB_REPO_NAME}/issues`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
        'User-Agent': 'twica-error-reporter',
      },
      body: JSON.stringify({ title, body, labels }),
    }
  )

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`GitHub API error: ${res.status} ${text}`)
  }

  const issue = await res.json() as { number: number; html_url: string }
  return { number: issue.number, url: issue.html_url }
}

/**
 * 既存 Issue にコメントを追加する（再発通知）。
 * 同じエラーが再発した場合、新規 Issue を作成せずに既存 Issue にコメントする。
 */
async function addCommentToIssue(
  issueNumber: number,
  group: ErrorGroup,
  env: Env
): Promise<void> {
  const body = `## Error Recurrence

**New occurrences**: ${group.count}x
**Last Seen**: ${group.lastSeen}

This error has reoccurred. Please investigate if still unresolved.`

  const res = await fetch(
    `https://api.github.com/repos/${env.GITHUB_REPO_OWNER}/${env.GITHUB_REPO_NAME}/issues/${issueNumber}/comments`,
    {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${env.GITHUB_TOKEN}`,
        'Accept': 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2022-11-28',
        'Content-Type': 'application/json',
        'User-Agent': 'twica-error-reporter',
      },
      body: JSON.stringify({ body }),
    }
  )

  if (!res.ok) {
    // コメント追加失敗時は throw して markErrorsAsProcessed をスキップする
    // throw しないとエラーが「処理済み」マークされ、GitHub Issue への追記が永久に失われる
    throw new Error(`Failed to add comment to issue #${issueNumber}: ${res.status}`)
  }
}

/**
 * Supabase REST API でエラーレコードを処理済みに更新する。
 * Supabase JS クライアントは使わず、fetch で直接 REST API を叩く
 * （Cron Worker のバンドルサイズを最小化するため）。
 */
async function markErrorsAsProcessed(
  errorIds: string[],
  issueNumber: number,
  issueUrl: string,
  env: Env
): Promise<void> {
  // Supabase REST API の IN フィルタ: id=in.(uuid1,uuid2,...)
  const idFilter = `in.(${errorIds.join(',')})`
  const url = `${env.SUPABASE_URL}/rest/v1/errors?id=${idFilter}`

  const res = await fetch(url, {
    method: 'PATCH',
    headers: {
      'apikey': env.SUPABASE_SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      'Content-Type': 'application/json',
      'Prefer': 'return=minimal',
    },
    body: JSON.stringify({
      github_issue_created: true,
      github_issue_number: issueNumber,
      github_issue_url: issueUrl,
    }),
  })

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Supabase PATCH error: ${res.status} ${text}`)
  }
}

/**
 * Supabase REST API から未処理エラーを取得する。
 * github_issue_created = false のエラーを古い順（FIFO）で最大100件取得。
 * 古い順にすることで、MAX_NEW_ISSUES_PER_RUN に達した場合でも
 * 新しいエラーが優先されて古いエラーが永久に未処理になる「飢餓状態」を防止する。
 */
async function fetchPendingErrors(env: Env): Promise<ErrorRecord[]> {
  const url = `${env.SUPABASE_URL}/rest/v1/errors?github_issue_created=eq.false&order=created_at.asc&limit=100`

  const res = await fetch(url, {
    headers: {
      'apikey': env.SUPABASE_SERVICE_ROLE_KEY,
      'Authorization': `Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,
      'Accept': 'application/json',
    },
  })

  if (!res.ok) {
    const text = await res.text()
    throw new Error(`Supabase fetch error: ${res.status} ${text}`)
  }

  return await res.json() as ErrorRecord[]
}

export default {
  /**
   * Cron Trigger ハンドラ: 5分ごとに実行される。
   * 1. Supabase から未処理エラーを取得
   * 2. エラーをシグネチャでグループ化（重複排除）
   * 3. 各グループについて既存 Issue を検索
   *    - 既存あり → コメント追加（再発通知）
   *    - 既存なし → 新規 Issue 作成
   * 4. Supabase でエラーを処理済みマーク
   */
  async scheduled(
    _event: ScheduledEvent,
    env: Env,
    _ctx: ExecutionContext
  ): Promise<void> {
    try {
      // 環境変数バリデーション: 未設定の場合は早期リターン
      if (!env.SUPABASE_URL || !env.SUPABASE_SERVICE_ROLE_KEY || !env.GITHUB_TOKEN) {
        console.error('[Error Reporter] Missing required secrets. Set SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, GITHUB_TOKEN via wrangler secret put')
        return
      }
      // GITHUB_REPO_OWNER / GITHUB_REPO_NAME は wrangler.toml の [vars] で定義
      // 未定義の場合 GitHub API の URL に undefined が含まれて予期しないエラーになる
      if (!env.GITHUB_REPO_OWNER || !env.GITHUB_REPO_NAME) {
        console.error('[Error Reporter] Missing GITHUB_REPO_OWNER or GITHUB_REPO_NAME in wrangler.toml [vars]')
        return
      }

      console.log('[Error Reporter] Cron job started')

      // 1. 未処理エラーを取得
      const errors = await fetchPendingErrors(env)

      if (errors.length === 0) {
        console.log('[Error Reporter] No pending errors')
        return
      }

      console.log(`[Error Reporter] Processing ${errors.length} errors`)

      // 2. エラーをシグネチャでグループ化
      const groups = await groupErrors(errors)
      console.log(`[Error Reporter] ${groups.length} unique error groups`)

      // 1回の Cron 実行で新規作成する Issue 数の上限
      // GitHub API レート制限（認証済み: 5,000 req/hour）を考慮し、
      // エラーバースト時の Issue 乱立を防止
      const MAX_NEW_ISSUES_PER_RUN = 5
      let newIssuesCreated = 0

      // 3. 各グループを処理
      for (const group of groups) {
        try {
          // 既存 Issue を検索（重複防止）
          const existing = await findExistingIssue(group.signature, env)

          let issueNumber: number
          let issueUrl: string

          if (existing) {
            // 既存 Issue にコメント追加（再発通知）
            issueNumber = existing.number
            issueUrl = existing.url
            await addCommentToIssue(issueNumber, group, env)
            console.log(`[Error Reporter] Added comment to existing issue #${issueNumber}`)
          } else {
            // 新規 Issue 作成数の上限チェック
            if (newIssuesCreated >= MAX_NEW_ISSUES_PER_RUN) {
              console.log(`[Error Reporter] Max new issues limit (${MAX_NEW_ISSUES_PER_RUN}) reached. Deferring group: ${group.signature}`)
              continue
            }
            // 新規 Issue 作成
            const issue = await createGitHubIssue(group, env)
            issueNumber = issue.number
            issueUrl = issue.url
            newIssuesCreated++
            console.log(`[Error Reporter] Created issue #${issueNumber}: ${issueUrl}`)
          }

          // 4. Supabase で処理済みマーク
          const errorIds = group.errors.map(e => e.id)
          await markErrorsAsProcessed(errorIds, issueNumber, issueUrl, env)
        } catch (err) {
          // 個別グループのエラーは他のグループの処理を阻害しない
          console.error(`[Error Reporter] Failed to process group ${group.signature}:`, err)
        }
      }

      console.log(`[Error Reporter] Cron job completed (${newIssuesCreated} new issues created)`)
    } catch (err) {
      // Cron job 全体のエラーは Cloudflare Workers Observability で確認可能
      console.error('[Error Reporter] Cron job failed:', err)
    }
  },
}
