-- Issue #557: per-pack collection completions.
-- The viewer collection page gains a pack filter and per-pack "complete!"
-- achievements. This migration adds the pack dimension to
-- collection_completions and makes rename_card_pack carry per-pack
-- achievements over to the renamed pack (implementing the "#557 で対応予定"
-- follow-up explicitly deferred in migration 00063).
--
-- 課題 #557: パック別コンプリート達成。視聴者向けコレクションページの
-- パックフィルタと、パック単位の「コンプリート！」実績を追加する。
-- collection_completions にパック次元 (collection_name) を追加し、
-- rename_card_pack のリネームカスケードに達成レコードの追従
-- (00063 で「#557 で対応予定」とした箇所) を実装する。

-- ---------------------------------------------------------------------------
-- a. collection_completions.collection_name: which pack this completion is
-- for. NULL = the pre-existing "overall collection complete" record (every
-- row that exists before this migration), so historical data keeps its
-- meaning without any backfill.
--
-- IF NOT EXISTS keeps the statement idempotent on re-run.
ALTER TABLE public.collection_completions
  ADD COLUMN IF NOT EXISTS collection_name TEXT NULL;

-- Length/blank rule mirrors the other collection_name-ish columns
-- (cards_collection_name_length in 00061): NULL allowed, otherwise 1-80
-- chars after trimming, as a last line of defense for direct DB writes.
--
-- Deliberately NOT adding a reserved-prefix guard like 00063's
-- cards_collection_name_not_reserved (`NOT LIKE '\_\_%'`): unlike
-- cards.collection_name, the DEFAULT_PACK_SENTINEL "__default__" is a
-- LEGITIMATE value in THIS column — it records "the default (unclassified)
-- pseudo-pack was completed", the same way the sentinel is already a valid
-- stored value in streamers.channel_point_collection_name and
-- streamer_additional_gacha_rewards.collection_name (see 00063's guard
-- comment for that precedent). A `__` ban here would reject correct data.
--
-- Drop-then-add keeps the constraint re-applicable (same idempotent pattern
-- as 00062/00063).
ALTER TABLE public.collection_completions
  DROP CONSTRAINT IF EXISTS collection_completions_collection_name_length;

ALTER TABLE public.collection_completions
  ADD CONSTRAINT collection_completions_collection_name_length
  CHECK (
    collection_name IS NULL
    OR char_length(btrim(collection_name)) BETWEEN 1 AND 80
  );

-- ---------------------------------------------------------------------------
-- b. Replace the original 3-column UNIQUE constraint with two partial unique
-- indexes so pack-scoped completions get their own uniqueness dimension.
--
-- The original constraint was declared INLINE (unnamed) in 00030's CREATE
-- TABLE, so its name was auto-generated by Postgres. Hard-coding a guessed
-- name in `DROP CONSTRAINT IF EXISTS` could silently no-op if the guess is
-- wrong (auto-generated names get truncated/uniquified), leaving BOTH the
-- old constraint and the new partial indexes active — pack rows would then
-- still collide with overall rows on (user, streamer, total_cards). Instead,
-- look the constraint up by its exact column SET via the catalogs and drop
-- whatever it is actually called. Idempotent: on re-run nothing matches and
-- the block is a no-op.
DO $$
DECLARE
  v_constraint_name TEXT;
BEGIN
  SELECT c.conname INTO v_constraint_name
  FROM pg_constraint c
  JOIN pg_class t ON t.oid = c.conrelid
  JOIN pg_namespace n ON n.oid = t.relnamespace
  WHERE n.nspname = 'public'
    AND t.relname = 'collection_completions'
    AND c.contype = 'u'
    -- Match the exact (order-insensitive) column set of the 00030 constraint:
    -- {twitch_user_id, streamer_id, total_cards}.
    AND (
      SELECT array_agg(a.attname ORDER BY a.attname)
      FROM unnest(c.conkey) AS k(attnum)
      JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = k.attnum
    ) = ARRAY['streamer_id', 'total_cards', 'twitch_user_id']::name[]
  LIMIT 1;

  IF v_constraint_name IS NOT NULL THEN
    EXECUTE format(
      'ALTER TABLE public.collection_completions DROP CONSTRAINT %I',
      v_constraint_name
    );
  END IF;
END
$$;

-- Overall (whole-collection) completions: collection_name IS NULL. Same
-- 3-column uniqueness as the dropped constraint, restricted to NULL rows —
-- every pre-existing row has collection_name NULL, so the semantics of
-- historical data are preserved exactly.
CREATE UNIQUE INDEX IF NOT EXISTS idx_collection_completions_overall_unique
  ON public.collection_completions (twitch_user_id, streamer_id, total_cards)
  WHERE collection_name IS NULL;

-- Pack-scoped completions: one record per (user, streamer, pack, pack size).
-- A NOT NULL partial index (rather than folding collection_name into a
-- single 4-column unique constraint) is required because in a plain UNIQUE
-- constraint NULLs never collide — two identical "overall" rows would both
-- be accepted, silently breaking the pre-#557 duplicate-prevention behavior.
CREATE UNIQUE INDEX IF NOT EXISTS idx_collection_completions_pack_unique
  ON public.collection_completions (twitch_user_id, streamer_id, collection_name, total_cards)
  WHERE collection_name IS NOT NULL;

-- ---------------------------------------------------------------------------
-- c. rename_card_pack: add the collection_completions cascade.
--
-- This CREATE OR REPLACE supersedes 00063's version (same signature). The
-- body below is 00063's verbatim, plus the completions cascade replacing the
-- "NOTE (#557 follow-up, deliberately out of scope here)" comment block —
-- this IS that follow-up. Product decision (issue #557): a completion earned
-- under the old pack name TRANSFERS to the renamed pack (achievements are
-- about the cards, which themselves move to the new name; forfeiting them on
-- a cosmetic rename would punish viewers for a streamer-side action).
--
-- All of 00063's design rationale (SECURITY INVOKER, locked search_path,
-- caller-side ownership checks, EXECUTE revoked from anon/authenticated)
-- carries over unchanged — see 00063 for the full discussion.
CREATE OR REPLACE FUNCTION public.rename_card_pack(
  p_streamer_id UUID,
  p_old_name TEXT,
  p_new_name TEXT
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_catalog JSONB;
  v_old_index INTEGER;
  v_new_name TEXT;
BEGIN
  -- Lock the streamer row for the duration of this transaction so a
  -- concurrent rename/catalog edit for the same streamer can't interleave
  -- with the read-modify-write below (classic lost-update race).
  SELECT card_pack_names INTO v_catalog
  FROM public.streamers
  WHERE id = p_streamer_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'STREAMER_NOT_FOUND';
  END IF;

  -- Defense-in-depth re-validation of the new name (the API route already
  -- validates this with the same rules before calling in, but the function
  -- must not trust its caller for anything that affects data integrity).
  v_new_name := btrim(p_new_name);
  IF v_new_name IS NULL OR char_length(v_new_name) < 1 OR char_length(v_new_name) > 80 THEN
    RAISE EXCEPTION 'INVALID_NEW_NAME';
  END IF;

  IF v_new_name LIKE '\_\_%' ESCAPE '\' THEN
    RAISE EXCEPTION 'RESERVED_NEW_NAME';
  END IF;

  IF p_old_name = v_new_name THEN
    RAISE EXCEPTION 'OLD_NEW_NAME_IDENTICAL';
  END IF;

  -- old must be a currently-registered catalog entry (find its array index
  -- so we can replace it in place with jsonb_set, preserving ordering).
  SELECT ordinality - 1 INTO v_old_index
  FROM jsonb_array_elements_text(v_catalog) WITH ORDINALITY AS t(name, ordinality)
  WHERE t.name = p_old_name
  LIMIT 1;

  IF v_old_index IS NULL THEN
    RAISE EXCEPTION 'OLD_NAME_NOT_FOUND';
  END IF;

  -- new must NOT already be a catalog entry (renaming onto an existing pack
  -- would silently merge two distinct packs' cards together).
  IF EXISTS (
    SELECT 1 FROM jsonb_array_elements_text(v_catalog) AS name WHERE name = v_new_name
  ) THEN
    RAISE EXCEPTION 'NEW_NAME_ALREADY_EXISTS';
  END IF;

  -- Replace the catalog entry in place (preserves display order) and cascade
  -- the rename to every table that stores a collection_name assignment
  -- scoped to this streamer. All statements run inside this function's
  -- implicit transaction, so a mid-way failure rolls back everything.
  UPDATE public.streamers
  SET card_pack_names = jsonb_set(v_catalog, ARRAY[v_old_index::text], to_jsonb(v_new_name))
  WHERE id = p_streamer_id;

  UPDATE public.cards
  SET collection_name = v_new_name
  WHERE streamer_id = p_streamer_id AND collection_name = p_old_name;

  UPDATE public.streamers
  SET channel_point_collection_name = v_new_name
  WHERE id = p_streamer_id AND channel_point_collection_name = p_old_name;

  UPDATE public.streamer_additional_gacha_rewards
  SET collection_name = v_new_name
  WHERE streamer_id = p_streamer_id AND collection_name = p_old_name;

  -- Issue #557: carry per-pack completion achievements over to the new name
  -- (the follow-up 00063 explicitly deferred with its "#557 で対応予定" note).
  --
  -- ORDER MATTERS — DELETE must run BEFORE the UPDATE below. The partial
  -- unique index idx_collection_completions_pack_unique forbids two rows
  -- with the same (twitch_user_id, streamer_id, collection_name,
  -- total_cards). If some user already holds a completion recorded under
  -- v_new_name with the same total_cards (e.g. the new name was used by a
  -- previously-deleted pack, or an earlier rename cycled names), UPDATE-ing
  -- their old-name row to v_new_name would raise a unique violation and roll
  -- back the ENTIRE rename (catalog + cards + reward cascades above) because
  -- of an unrelated historical coincidence. So first DELETE exactly those
  -- old-name rows whose destination slot is already occupied — the surviving
  -- pre-existing new-name row already records the same achievement, so no
  -- information is lost — then UPDATE the remaining, collision-free rows.
  DELETE FROM public.collection_completions old_cc
  WHERE old_cc.streamer_id = p_streamer_id
    AND old_cc.collection_name = p_old_name
    AND EXISTS (
      SELECT 1
      FROM public.collection_completions new_cc
      WHERE new_cc.streamer_id = p_streamer_id
        AND new_cc.collection_name = v_new_name
        AND new_cc.twitch_user_id = old_cc.twitch_user_id
        AND new_cc.total_cards = old_cc.total_cards
    );

  UPDATE public.collection_completions
  SET collection_name = v_new_name
  WHERE streamer_id = p_streamer_id AND collection_name = p_old_name;
END;
$$;

-- Re-assert the grants from 00063. CREATE OR REPLACE preserves existing
-- privileges, but repeating them keeps this migration self-contained and
-- correct even if the function had been dropped/recreated out of band —
-- only the service_role admin client (src/lib/supabase/admin.ts) may call
-- this RPC (see 00063's SECURITY INVOKER discussion).
REVOKE ALL ON FUNCTION public.rename_card_pack(UUID, TEXT, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.rename_card_pack(UUID, TEXT, TEXT) TO service_role;
