import { describe, expect, it } from 'vitest'
import {
  buildReviewComment,
  MAX_BODY_LENGTH,
  redactSecrets,
  truncateAndCloseFences,
} from '../../.github/scripts/format-review.mjs'

describe('claude-review format helpers', () => {
  describe('redactSecrets', () => {
    it('redacts known token formats', () => {
      const input =
        'sk-ant-api03-abcdefghij0123456789 / ghp_12345678901234567890123456 / github_pat_11111_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      const out = redactSecrets(input)
      expect(out).not.toContain('sk-ant-api03')
      expect(out).not.toContain('ghp_12345678901234567890123456')
      expect(out).not.toContain('github_pat_11111')
      expect(out.match(/\[REDACTED\]/g)).toHaveLength(3)
    })

    it('leaves normal text and short identifiers untouched', () => {
      const input = 'actions/checkout@v4 と短いトークン ghp_12345 はそのまま'
      expect(redactSecrets(input)).toBe(input)
    })
  })

  describe('truncateAndCloseFences', () => {
    it('closes an unclosed fence even without truncation', () => {
      expect(truncateAndCloseFences('```js\nconst x = 1')).toBe('```js\nconst x = 1\n```')
    })

    it('keeps balanced fences untouched', () => {
      const text = '```js\nconst x = 1\n```'
      expect(truncateAndCloseFences(text)).toBe(text)
    })

    it('truncates long output and appends a note', () => {
      const long = `${'x'.repeat(MAX_BODY_LENGTH + 50)}\nlast`
      const out = truncateAndCloseFences(long)
      expect(out).toContain('（長すぎるため省略）')
      expect(Array.from(out).length).toBeLessThan(MAX_BODY_LENGTH + 50)
    })

    it('does not split surrogate pairs when truncating', () => {
      const out = truncateAndCloseFences('😀'.repeat(MAX_BODY_LENGTH + 10))
      expect(out.includes('\uFFFD')).toBe(false)
    })
  })

  describe('buildReviewComment', () => {
    it('includes marker, reviewed commit link and footer', () => {
      const body = buildReviewComment({
        marker: '<!-- claude-auto-review-preview -->',
        shortSha: 'abc1234',
        commitUrl: 'https://github.com/azumag/twica/commit/abc1234',
        reviewText: '指摘なし',
      })
      expect(body.startsWith('<!-- claude-auto-review-preview -->\n## Claude Auto Review')).toBe(
        true,
      )
      expect(body).toContain(
        'Reviewed commit: [`abc1234`](https://github.com/azumag/twica/commit/abc1234)',
      )
      expect(body).toContain('指摘なし')
      expect(body).toContain('*Generated by Claude Code (opus)*')
    })
  })
})
