import { describe, expect, it } from 'vitest'
import {
  buildReviewComment,
  MAX_BODY_LENGTH,
  redactSecrets,
  truncateAndCloseFences,
} from '../../.github/scripts/format-review.mjs'

describe('claude-review format helpers', () => {
  describe('redactSecrets', () => {
    it('redacts known token formats', () => {
      const input =
        'sk-ant-api03-abcdefghij0123456789 / ghp_12345678901234567890123456 / github_pat_11111_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      const out = redactSecrets(input)
      expect(out).not.toContain('sk-ant-api03')
      expect(out).not.toContain('ghp_12345678901234567890123456')
      expect(out).not.toContain('github_pat_11111')
      expect(out.match(/\[REDACTED\]/g)).toHaveLength(3)
    })

    it('leaves normal text and short identifiers untouched', () => {
      const input = 'actions/checkout@v4 と短いトークン ghp_12345 はそのまま'
      expect(redactSecrets(input)).toBe(input)
    })
  })

  describe('truncateAndCloseFences', () => {
    it('closes an unclosed fence even without truncation', () => {
      expect(truncateAndCloseFences('```js\nconst x = 1')).toBe('```js\nconst x = 1\n```')
    })

    it('keeps balanced fences untouched', () => {
      const text = '```js\nconst x = 1\n```'
      expect(truncateAndCloseFences(text)).toBe(text)
    })

    it('truncates long output and appends a note', () => {
      const long = `${'x'.repeat(MAX_BODY_LENGTH + 50)}\nlast`
      const out = truncateAndCloseFences(long)
      expect(out).toContain('（長すぎるため省略）')
      expect(Array.from(out).length).toBeLessThan(MAX_BODY_LENGTH + 50)
    })

    it('does not split surrogate pairs when truncating', () => {
      const out = truncateAndCloseFences('😀'.repeat(MAX_BODY_LENGTH + 10))
      expect(out.includes('\uFFFD')).toBe(false)
    })

    it('cuts at a line boundary when a newline is within the limit', () => {
      const out = truncateAndCloseFences('a\n'.repeat(MAX_BODY_LENGTH))
      expect(out.endsWith('（長すぎるため省略）')).toBe(true)
      // 注記の直前が改行 = 途中の行を残さず行境界で切れている
      expect(out.slice(0, out.indexOf('（長すぎるため省略）')).endsWith('\n')).toBe(true)
    })

    it('closes a fence opened before the cut and keeps the note outside', () => {
      const out = truncateAndCloseFences('```js\n' + 'x\n'.repeat(MAX_BODY_LENGTH))
      expect(out).toContain('（長すぎるため省略）')
      // 閉じフェンスが注記より前に来る = 注記はコードブロックの外
      expect(out.lastIndexOf('```')).toBeLessThan(out.indexOf('（長すぎるため省略）'))
    })

    it('does not truncate when the length is exactly at the limit', () => {
      const text = 'a'.repeat(MAX_BODY_LENGTH)
      expect(truncateAndCloseFences(text)).toBe(text)
    })
  })

  describe('redactSecrets edge cases', () => {
    it('greedily consumes trailing token characters (over-redaction is safe)', () => {
      const input = 'sk-ant-api03-abcdefghij0123456789X'
      expect(redactSecrets(input)).toBe('[REDACTED]')
    })

    it('redacts tokens embedded in multi-line text', () => {
      const input = 'line1 sk-ant-api03-abcdefghij0123456789\nline2'
      const out = redactSecrets(input)
      expect(out).toContain('[REDACTED]')
      expect(out).not.toContain('sk-ant-api03')
    })

    it('is idempotent', () => {
      const once = redactSecrets('sk-ant-api03-abcdefghij0123456789')
      expect(redactSecrets(once)).toBe(once)
    })
  })

  describe('buildReviewComment', () => {
    it('includes marker, reviewed commit link and footer', () => {
      const body = buildReviewComment({
        marker: '<!-- claude-auto-review-preview -->',
        shortSha: 'abc1234',
        commitUrl: 'https://github.com/azumag/twica/commit/abc1234',
        reviewText: '指摘なし',
      })
      expect(body.startsWith('<!-- claude-auto-review-preview -->\n## Claude Auto Review')).toBe(
        true,
      )
      expect(body).toContain(
        'Reviewed commit: [`abc1234`](https://github.com/azumag/twica/commit/abc1234)',
      )
      expect(body).toContain('指摘なし')
      expect(body).toContain('*Generated by Claude Code (opus)*')
    })
  })
})
