import { describe, expect, it } from 'vitest'
import {
  buildReviewCommentBody,
  isOwnReviewComment,
  MAX_BODY_LENGTH,
  redactSecrets,
  truncateAndCloseFences,
} from '../../.github/scripts/format-review.mjs'

describe('claude-review format helpers', () => {
  describe('redactSecrets', () => {
    it('redacts known token formats', () => {
      const input =
        'sk-ant-api03-abcdefghij0123456789 / ghp_12345678901234567890123456 / github_pat_11111_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'
      const out = redactSecrets(input)
      expect(out).not.toContain('sk-ant-api03')
      expect(out).not.toContain('ghp_12345678901234567890123456')
      expect(out).not.toContain('github_pat_11111')
      expect(out.match(/\[REDACTED\]/g)).toHaveLength(3)
    })

    it('leaves normal text and short identifiers untouched', () => {
      const input = 'actions/checkout@v4 と短いトークン ghp_12345 はそのまま'
      expect(redactSecrets(input)).toBe(input)
    })

    it('redacts the claude setup-token OAuth format (sk-ant-oat01-)', () => {
      expect(redactSecrets('sk-ant-oat01-abcdefghij0123456789')).toBe('[REDACTED]')
    })

    it('greedily consumes trailing token characters (over-redaction is safe)', () => {
      const input = 'sk-ant-api03-abcdefghij0123456789X'
      expect(redactSecrets(input)).toBe('[REDACTED]')
    })

    it('redacts tokens that follow a word character (no leading boundary)', () => {
      expect(redactSecrets('Xsk-ant-api03-abcdefghij0123456789')).toBe('X[REDACTED]')
    })

    it('redacts ghp_ tokens even when followed by an underscore', () => {
      expect(redactSecrets('ghp_AAAAAAAAAAAAAAAAAAAAAAAAAAAAA_')).toBe('[REDACTED]_')
    })

    it('redacts github_pat_ tokens even when followed by a hyphen', () => {
      expect(redactSecrets('github_pat_11111_AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA-')).toBe(
        '[REDACTED]-',
      )
    })

    it('redacts all gh*_ token prefixes (p, o, u, s, r)', () => {
      for (const prefix of ['ghp_', 'gho_', 'ghu_', 'ghs_', 'ghr_']) {
        expect(redactSecrets(prefix + 'A'.repeat(24))).toBe('[REDACTED]')
      }
    })

    it('redacts tokens embedded in multi-line text', () => {
      const input = 'line1 sk-ant-api03-abcdefghij0123456789\nline2'
      const out = redactSecrets(input)
      expect(out).toContain('[REDACTED]')
      expect(out).not.toContain('sk-ant-api03')
    })

    it('is idempotent', () => {
      const once = redactSecrets('sk-ant-api03-abcdefghij0123456789')
      expect(redactSecrets(once)).toBe(once)
    })
  })

  describe('truncateAndCloseFences', () => {
    it('keeps text unchanged within the limit', () => {
      const text = '```js\nconst x = 1\n```'
      expect(truncateAndCloseFences(text)).toBe(text)
    })

    it('appends a note on overflow and stays within the limit plus overhead', () => {
      const out = truncateAndCloseFences('x'.repeat(MAX_BODY_LENGTH + 50))
      expect(out).toContain('（長すぎるため省略）')
      expect(out.length).toBeLessThanOrEqual(MAX_BODY_LENGTH + 16)
    })
  })

  describe('buildReviewCommentBody', () => {
    const base = {
      marker: '<!-- claude-auto-review-preview -->',
      shortSha: 'abc1234',
      commitUrl: 'https://github.com/azumag/twica/commit/abc1234',
      runUrl: 'https://github.com/azumag/twica/actions/runs/12345',
    }

    it('includes marker, reviewed commit link and footer', () => {
      const body = buildReviewCommentBody({ ...base, reviewText: '指摘なし' })
      expect(body.startsWith('<!-- claude-auto-review-preview -->\n## Claude Auto Review')).toBe(
        true,
      )
      expect(body).toContain(
        'Reviewed commit: [`abc1234`](https://github.com/azumag/twica/commit/abc1234)',
      )
      expect(body).toContain('指摘なし')
      expect(body).toContain(
        '*Generated by Claude Code (opus) · [Run](https://github.com/azumag/twica/actions/runs/12345)*',
      )
    })

    it('redacts secrets before assembling the body (order guard)', () => {
      const body = buildReviewCommentBody({
        ...base,
        reviewText: 'トークン: sk-ant-api03-abcdefghij0123456789',
      })
      expect(body).not.toContain('sk-ant-api03')
      expect(body).toContain('[REDACTED]')
    })

    it('stays far below the issue comment limit even with max-length review text', () => {
      const body = buildReviewCommentBody({
        ...base,
        reviewText: 'x'.repeat(MAX_BODY_LENGTH + 5000),
      })
      // 切り詰めが効いていれば本文は MAX + ヘッダ/フッタ程度に収まる
      expect(Array.from(body).length).toBeLessThanOrEqual(MAX_BODY_LENGTH + 400)
    })

    it('round-trips with isOwnReviewComment using the marker line', () => {
      const body = buildReviewCommentBody({ ...base, reviewText: '指摘なし' })
      expect(
        isOwnReviewComment(
          { user: { login: 'github-actions[bot]', type: 'Bot' }, body },
          base.marker,
        ),
      ).toBe(true)
    })
  })

  describe('isOwnReviewComment', () => {
    const marker = '<!-- claude-auto-review-preview -->'

    it('accepts a bot comment whose first line is the marker', () => {
      expect(
        isOwnReviewComment(
          {
            user: { login: 'github-actions[bot]', type: 'Bot' },
            body: `${marker}\n## Claude Auto Review`,
          },
          marker,
        ),
      ).toBe(true)
    })

    it('accepts CRLF line endings in the first line', () => {
      expect(
        isOwnReviewComment(
          {
            user: { login: 'github-actions[bot]', type: 'Bot' },
            body: `${marker}\r\n## Claude Auto Review`,
          },
          marker,
        ),
      ).toBe(true)
    })

    it('rejects other bots even with the marker', () => {
      expect(
        isOwnReviewComment(
          {
            user: { login: 'renovate[bot]', type: 'Bot' },
            body: `${marker}\n## Claude Auto Review`,
          },
          marker,
        ),
      ).toBe(false)
    })

    it('rejects non-bot authors', () => {
      expect(
        isOwnReviewComment(
          {
            user: { login: 'azumag', type: 'User' },
            body: `${marker}\n## Claude Auto Review`,
          },
          marker,
        ),
      ).toBe(false)
    })

    it('rejects comments whose first line is not the marker', () => {
      expect(
        isOwnReviewComment(
          {
            user: { login: 'github-actions[bot]', type: 'Bot' },
            body: '## Claude Auto Review',
          },
          marker,
        ),
      ).toBe(false)
    })

    it('handles missing body or comment safely', () => {
      expect(isOwnReviewComment({ user: { login: 'github-actions[bot]' } }, marker)).toBe(false)
      expect(isOwnReviewComment(undefined, marker)).toBe(false)
    })
  })
})
